# Generated by Django 5.0.1 on 2025-11-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Disposition code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Disposition name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of disposition', null=True)),
                ('category', models.CharField(choices=[('inquiry', 'General Inquiry'), ('service', 'Service Request'), ('sales', 'Sales Inquiry'), ('complaint', 'Complaint'), ('followup', 'Follow-up'), ('test_drive', 'Test Drive Request'), ('booking', 'Vehicle Booking'), ('finance', 'Finance Inquiry'), ('other', 'Other')], default='inquiry', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_followup', models.BooleanField(default=False, help_text='Does this disposition require follow-up?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call Disposition',
                'verbose_name_plural': 'Call Dispositions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IncomingCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(help_text='Unique call identifier', max_length=100, unique=True)),
                ('call_sid', models.CharField(blank=True, help_text='Call SID from provider', max_length=100, null=True)),
                ('caller_number', models.CharField(help_text="Caller's phone number", max_length=20)),
                ('caller_name', models.CharField(blank=True, help_text="Caller's name", max_length=200, null=True)),
                ('call_start_time', models.DateTimeField(help_text='When call started')),
                ('call_end_time', models.DateTimeField(blank=True, help_text='When call ended', null=True)),
                ('call_duration', models.IntegerField(default=0, help_text='Call duration in seconds')),
                ('call_status', models.CharField(choices=[('ringing', 'Ringing'), ('answered', 'Answered'), ('busy', 'Busy'), ('no-answer', 'No Answer'), ('failed', 'Failed'), ('completed', 'Completed')], default='ringing', max_length=50)),
                ('staff_name', models.CharField(blank=True, help_text='Staff member who handled call', max_length=200, null=True)),
                ('staff_id', models.CharField(blank=True, help_text='Staff ID', max_length=50, null=True)),
                ('recording_url', models.URLField(blank=True, help_text='Call recording URL', null=True)),
                ('disposition_notes', models.TextField(blank=True, help_text='Additional notes about disposition', null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('vehicle_model', models.CharField(blank=True, help_text='Vehicle model of interest', max_length=100, null=True)),
                ('vehicle_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('is_lead', models.BooleanField(default=False, help_text='Is this a potential lead?')),
                ('lead_quality', models.CharField(blank=True, choices=[('hot', 'Hot Lead'), ('warm', 'Warm Lead'), ('cold', 'Cold Lead')], max_length=20, null=True)),
                ('raw_webhook_data', models.JSONField(blank=True, help_text='Raw webhook data received', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='callmanagement.calldisposition')),
            ],
            options={
                'verbose_name': 'Incoming Call',
                'verbose_name_plural': 'Incoming Calls',
                'ordering': ['-call_start_time'],
            },
        ),
        migrations.CreateModel(
            name='CallNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Note content')),
                ('created_by', models.CharField(blank=True, help_text='Who created this note', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='callmanagement.incomingcall')),
            ],
            options={
                'verbose_name': 'Call Note',
                'verbose_name_plural': 'Call Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
