# Generated by Django 5.0.1 on 2025-11-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingcall',
            name='recording_url',
            field=models.URLField(blank=True, help_text='Call recording URL', max_length=500, null=True),
        ),
    ]
